# NFC Links Service Docker Compose
# Deploy to: get.biz365.ai

version: '3.8'

services:
  nfc-links:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biz365-nfc-links
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - API_BASE_URL=https://api.biz365.ai
      - DATABASE_URL=postgresql://biz365_user:asdfghjkl@89.117.75.191:5432/biz365
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
        reservations:
          memory: 64M
          cpus: '0.05'
